#!/bin/bash
# Display basic system info when logging in to a cpanel server
# Adapted by Josh King <josh@joshuaking.org>
REVISION=0.1;

if [ ! -d "/root/.cpanel" ]; then
        echo "Exiting.  This is not a cPanel Machine."
        exit 1
fi

#set colors
red='\E[1;31m';
yellow='\E[1;33m';
green='\E[1;32m';
white='e[1;37m';
normal='tput sgr0';

#get primary ip
IPADDR=`/sbin/ifconfig eth0 | grep -m 1 'inet' | cut -f2 |awk '{ print $2}'`
WHMVER=`/usr/local/cpanel/cpanel -V`
#Get Basic OS Info
KERNFO=`uname -or`
OSVER=`cat /etc/redhat-release | awk '{ print $1,$4}'`

#Get in depth info on IO
#Normally unless run in realtime, these stats are fairly useless for me. Enable if you want them
#IOCT=`iostat -txN | sed -n '6,21p'`
#Memory use
MEMCT=`/bin/free -h -m -t`
# TOP CPU
TCU=`ps aux | awk '{print $2, "\t"$3,"\t" $11}' | sort -k2r | head -n 5`
#TOP RAM
TRAM=` ps aux | awk '{print $2, "\t"$4,"\t" $11}' | sort -k2r | head -n 5`

###
### BEGIN APACHE SECTION
###

#tests if apache is active or not, if port 80 is open on server, then assumes apache is online, if 0 apache offline
APACHEACTIVE=`netstat -na |grep :80 |grep LISTEN |wc -l`
if [ "$APACHEACTIVE" == "0" ]; then
        APACHEONLINE="NO"
   else
        APACHEONLINE="YES"
   fi

if [ "$APACHEONLINE" == "YES" ]; then
        APACHEVERSION=`httpd -v |grep version |awk '{ print $3}' |cut -c 8-13`
        APACHECONNECTS=`netstat -n | grep :80 |wc -l`
        APACHEOUTPUT="$APACHEVERSION Online / Current Connections $APACHECONNECTS"
   else
        APACHEOUTPUT="OFFLINE"
   fi

###
### BEGIN MYSQL SECTION
###

MYSQLACTIVE=`systemctl status mysql | grep Active | awk '{ print $3}'`
if [ "$MYSQLACTIVE" = "(running)" ]; then
        MYSQLVERSION=`mysql -V | awk '{ print $5}' | cut -d ',' -f 1`
        MYSQLPROCESSES=`mysqladmin status |awk '{ print $4}'`
        MYSQLOUTPUT="$MYSQLVERSION Online / Active Threads: $MYSQLPROCESSES"
   else
        MYSQLOUTPUT="OFFLINE"
   fi

###
### BEGIN EXIM SECTION
###

EXIMACTIVE=`systemctl status exim | grep Active | awk '{ print $3}'`
if [ "$EXIMACTIVE" = "(running)" ]; then
        MAILMSGS=`exim -bpc`
        EXIMOUTPUT="Online / Messages in Queue: $MAILMSGS"
   else
        EXIMOUTPUT="OFFLINE"
   fi

PHPVERSION=`php -v |grep cli |awk '{ print $2}'`

###
### DISPLAY SUMMARY INFORMATION
###
echo " ######################## HERE IS THE CURRENT #######################"
echo " ########################## SYSTEM SUMMARY ##########################"
 uptime
echo ""
echo " Hostname:    $HOSTNAME"
echo " Primary IP:  $IPADDR"
echo ""
echo " System Version Information"
echo " ------------------------------"
echo " WHM Version: $WHMVER"
echo " PHP Version: $PHPVERSION"
echo " Kernel base: $KERNFO"
echo " OS Version : $OSVER"
echo ""
echo " Service Summary"
echo " ------------------------------"
echo " Apache $APACHEOUTPUT"
echo " MySQL $MYSQLOUTPUT"
echo " Exim $EXIMOUTPUT"
echo ""
echo ""
echo " ######################### EXTENDED INFORMATION #####################"
echo ""
echo " ---Top PID CPU USEAGE---"
echo "   $TCU"
echo " ---Top PID RAM USAGE---"
echo "   $TRAM"
echo " ---SYSTEM MEMORY USAGE---"
echo "    $MEMCT"
#echo "-- IOstat RECORD (RUN INTERACTIVELY FOR REALTIME COUNTS)---"
#echo "   $IOCT"
